apiVersion: apps/v1
kind: Deployment
metadata:
  name: bryan-devops-deployment 
spec:
  replicas: 2 
  selector:
    matchLabels:
      app: bryan-devops 
  template:
    metadata:
      labels:
        app: bryan-devops 
    spec:
      containers:
        - name: bryan-devops 
          image: bryan-devops:{{BUILD_NUMBER}}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5050 
