apiVersion: v1
kind: Service
metadata:
  name: bryan-devops
spec:
  type: NodePort 
  selector:
    app: bryan-devops 
  ports:
    - protocol: TCP
      port: 5050 
      targetPort: 5050 
      nodePort: 30080 